import Head from 'next/head';
import Card from '../components/Card';
import Cta from '../components/Cta';
import Div from '../components/Div';
import FunFact from '../components/FunFact';
import Hero from '../components/Hero';
import Layout from '../components/Layout';
import LogoList from '../components/LogoList';
import MovingText from '../components/MovingText';
import SectionHeading from '../components/SectionHeading';
import PortfolioSlider from '../components/Slider/PortfolioSlider';
import PostSlider from '../components/Slider/PostSlider';
import TeamSlider from '../components/Slider/TeamSlider';
import TestimonialSlider from '../components/Slider/TestimonialSlider';
import TimelineSlider from '../components/Slider/TimelineSlider';
import Spacing from '../components/Spacing';
import VideoModal from '../components/VideoModal';
import Fade from 'react-reveal/Fade'
import Zoom from 'react-reveal/Zoom'
import React from 'react';
import { useEffect } from 'react';
import AOS from 'aos';
import config from 'react-reveal/globals';

config({ ssrFadeout: true });

export default function Home() {
  React.useEffect(() => {
    AOS.init();
  }, []);
  // Hero Social Links
  const heroSocialLinks = [
    {
      name: 'Reddit',
      links: '/',
    },
  ];

  // FunFact Data
  const funfaceData = [
    {
      title: 'Global Happy Clients',
      factNumber: '40K',
    },
    {
      title: 'Project Completed',
      factNumber: '50K',
    },
    {
      title: 'Team Members',
      factNumber: '245',
    },
    {
      title: 'Digital products',
      factNumber: '550',
    },
  ];

  return (
    <>
      <Head>
        <title>Home - Creative Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Hero Section */}
        <Hero
          title="Explore Our Server Ranks and Rewards"
          subtitle="Join Our Gaming Community and Unlock Exclusive Benefits with Our Server Ranks!"
          btnText="Join Discord"
          btnLink="/contact"
          scrollDownId="#service"
          socialLinksHeading="Follow Us"
          heroSocialLinks={heroSocialLinks}
          bgImageUrl="/images/hero_bg.jpeg"
        />
        {/* End Hero Section */}
        <Spacing lg="100" md="80" />
        <Div className="container" id="about">
          <Div className="row">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-image_layer cs-style1">
                <Zoom ssrFadeout>
                <Div className="cs-image_layer_in">
                <Fade ssrFadeout left>
                  <img
                    src="/images/Hblack.png"
                    alt="About"
                    className="w-100 cs-radius_15"
                  />
                   </Fade>
                </Div>
                </Zoom>
               
              </Div>
              <Spacing lg="0" md="40" />
            </Div>
            
            <Div className="col-xl-5 offset-xl-1 col-lg-6">
            <Fade right ssrFadeout delay={1000}>
              <SectionHeading
                title="Welcome to our Gaming Community: Join the Fun!"
                subtitle="About Us"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                We offer a range of ranks on our server, each with its unique perks and privileges. Our ranks are designed to reward our players for their loyalty and dedication to our server. The higher your rank, the more benefits you will receive, such as access to exclusive areas, special commands, and items.
                </p>
                <Spacing lg="15" md="15" />
                <p className="cs-m0">
                We believe that our ranking system is a great way to reward our players for their loyalty and dedication to our server. It's also an excellent way to promote healthy competition and give players a sense of accomplishment. We hope you enjoy your time on our server and look forward to seeing you in-game!
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="0" />
              </SectionHeading>
              </Fade>
            </Div>
           
          </Div>
        </Div>
        {/* Start CTA Section */}
        <Div className="container">
          <Cta
            title="Let’s discuss"
            btnText="Contact Our Team"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
